/* Visual Archive Data Catalog */
window.GALLERY_DATA = [
  {
    "id": "19th-birthday",
    "slug": "19th-birthday",
    "title": "19th Birthday Editorial Shoot",
    "client": "Bebe's 19th Birthday",
    "category": "portraits",
    "categoryLabel": "PORTRAITS",
    "date": "2026",
    "location": "Davao Region, Philippines",
    "cover": "assets/gallery/19th-birthday/full/photo-1.jpg",
    "coverThumb": "assets/gallery/19th-birthday/thumb/photo-1.jpg",
    "tagline": "Golden hour portraiture & natural outdoor light.",
    "description": "An intimate outdoor birthday portrait session centered around warm afternoon ambient lighting, unhurried posing, and clean tonal depth.",
    "primaryCamera": "Nikon Full-Frame",
    "primaryLens": "55mm \u0192/1.8 Prime",
    "lightingSetup": "Natural Ambient \u00b7 Golden Hour Sunset",
    "colorScience": "Adobe Lightroom Classic \u00b7 Warm Editorial Emulation",
    "photos": [
      {
        "id": "19th-1",
        "title": "Sunlit Portrait in the Meadow",
        "filename": "photo-1.jpg",
        "full": "assets/gallery/19th-birthday/full/photo-1.jpg",
        "thumb": "assets/gallery/19th-birthday/thumb/photo-1.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/1.8 \u00b7 1/800s \u00b7 ISO 100",
        "lighting": "Direct Golden Hour Sunlight",
        "colorProfile": "Warm Tonal Grade \u00b7 Soft Highlights",
        "caption": "Low-angle framing accentuating the golden sunlight filtering through the background foliage."
      },
      {
        "id": "19th-2",
        "title": "Overcast Soft Frame",
        "filename": "photo-2.jpg",
        "full": "assets/gallery/19th-birthday/full/photo-2.jpg",
        "thumb": "assets/gallery/19th-birthday/thumb/photo-2.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.0 \u00b7 1/640s \u00b7 ISO 125",
        "lighting": "Diffused Ambient Daylight",
        "colorProfile": "Natural Skin Tones \u00b7 Subtle Contrast",
        "caption": "Medium close-up focusing on natural expression and soft falloff."
      },
      {
        "id": "19th-3",
        "title": "Candid Silhouette & Depth",
        "filename": "photo-3.jpg",
        "full": "assets/gallery/19th-birthday/full/photo-3.jpg",
        "thumb": "assets/gallery/19th-birthday/thumb/photo-3.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/1.8 \u00b7 1/1000s \u00b7 ISO 100",
        "lighting": "Backlit Rim Sunlight",
        "colorProfile": "Film Curve \u00b7 Lifted Blacks",
        "caption": "Natural backlit halo effect accentuating subject separation from the greenery."
      },
      {
        "id": "19th-4",
        "title": "Editorial Stance",
        "filename": "photo-4.jpg",
        "full": "assets/gallery/19th-birthday/full/photo-4.jpg",
        "thumb": "assets/gallery/19th-birthday/thumb/photo-4.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.2 \u00b7 1/500s \u00b7 ISO 160",
        "lighting": "Side Window / Open Shade",
        "colorProfile": "Neutral Matte \u00b7 Muted Greens",
        "caption": "Full-body composition balancing subject posture and environmental architecture."
      },
      {
        "id": "19th-5",
        "title": "Intimate Close-Up",
        "filename": "photo-5.jpg",
        "full": "assets/gallery/19th-birthday/full/photo-5.jpg",
        "thumb": "assets/gallery/19th-birthday/thumb/photo-5.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/1.8 \u00b7 1/1250s \u00b7 ISO 100",
        "lighting": "Golden Hour Ambient",
        "colorProfile": "Warm Amber Grade",
        "caption": "Tight framing isolating eye contact and shallow optical depth of field."
      }
    ]
  },
  {
    "id": "avianna-birthday",
    "slug": "avianna-birthday",
    "title": "Avianna's First Birthday Shoot",
    "client": "Avianna & Family",
    "category": "documentary",
    "categoryLabel": "DOCUMENTARY / FAMILY",
    "date": "2026",
    "location": "Digos City, Philippines",
    "cover": "assets/gallery/avianna-birthday/full/photo-1.jpg",
    "coverThumb": "assets/gallery/avianna-birthday/thumb/photo-1.jpg",
    "tagline": "Milestone family documentary and toddler candid frames.",
    "description": "Capturing the joy, innocence, and fleeting milestone moments of a child's very first birthday celebration with close family.",
    "primaryCamera": "Nikon Full-Frame",
    "primaryLens": "35mm & 55mm Fast Primes",
    "lightingSetup": "Natural Indoor Window Light \u00b7 Soft Fill",
    "colorScience": "Clean Pastel & True Skin Tones",
    "photos": [
      {
        "id": "av-1",
        "title": "Birthday Milestone Smile",
        "filename": "photo-1.jpg",
        "full": "assets/gallery/avianna-birthday/full/photo-1.jpg",
        "thumb": "assets/gallery/avianna-birthday/thumb/photo-1.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.0 \u00b7 1/400s \u00b7 ISO 200",
        "lighting": "Soft Diffused Daylight",
        "colorProfile": "Bright & Clean Tonal Balance",
        "caption": "Spontaneous toddler laughter captured at eye level."
      },
      {
        "id": "av-2",
        "title": "Curiosity & Wonder",
        "filename": "photo-2.jpg",
        "full": "assets/gallery/avianna-birthday/full/photo-2.jpg",
        "thumb": "assets/gallery/avianna-birthday/thumb/photo-2.jpg",
        "lens": "35mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.2 \u00b7 1/320s \u00b7 ISO 250",
        "lighting": "Window Light",
        "colorProfile": "True-to-Life Skin Rendition",
        "caption": "Candid documentary frame capturing child exploration."
      },
      {
        "id": "av-3",
        "title": "Celebration Details",
        "filename": "photo-3.jpg",
        "full": "assets/gallery/avianna-birthday/full/photo-3.jpg",
        "thumb": "assets/gallery/avianna-birthday/thumb/photo-3.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/1.8 \u00b7 1/500s \u00b7 ISO 160",
        "lighting": "Ambient Room Light",
        "colorProfile": "Pastel Color Science",
        "caption": "Festive decor details and warm ambient atmosphere."
      },
      {
        "id": "av-4",
        "title": "Mother's Embrace",
        "filename": "photo-4.jpg",
        "full": "assets/gallery/avianna-birthday/full/photo-4.jpg",
        "thumb": "assets/gallery/avianna-birthday/thumb/photo-4.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.0 \u00b7 1/250s \u00b7 ISO 320",
        "lighting": "Soft Window Glow",
        "colorProfile": "Gentle Warmth \u00b7 Low Contrast",
        "caption": "Unposed emotional connection between parent and child."
      },
      {
        "id": "av-5",
        "title": "The First Birthday Cake",
        "filename": "photo-5.jpg",
        "full": "assets/gallery/avianna-birthday/full/photo-5.jpg",
        "thumb": "assets/gallery/avianna-birthday/thumb/photo-5.jpg",
        "lens": "35mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.5 \u00b7 1/200s \u00b7 ISO 400",
        "lighting": "Warm Ambient",
        "colorProfile": "Rich Vivid Highlights",
        "caption": "Cake smash anticipation and candid expressions."
      }
    ]
  },
  {
    "id": "christening",
    "slug": "christening",
    "title": "Sacred Christening Ceremony",
    "client": "Family Baptismal Archive",
    "category": "christening",
    "categoryLabel": "CHRISTENING / SACRED",
    "date": "2026",
    "location": "Digos City Cathedral, Philippines",
    "cover": "assets/gallery/christening/full/photo-1.jpg",
    "coverThumb": "assets/gallery/christening/thumb/photo-1.jpg",
    "tagline": "Reverent documentary capture of baptismal traditions.",
    "description": "Subtle, non-intrusive photojournalism inside the church preserving holy water rites, godparent vows, and family gatherings.",
    "primaryCamera": "Nikon Full-Frame",
    "primaryLens": "35mm \u0192/1.8 & 55mm \u0192/1.8",
    "lightingSetup": "Cathedral Stained Glass & Ambient Sanctuary Lighting",
    "colorScience": "Rich Monochrome & Warm Documentary Curves",
    "photos": [
      {
        "id": "ch-1",
        "title": "The Holy Water Rite",
        "filename": "photo-1.jpg",
        "full": "assets/gallery/christening/full/photo-1.jpg",
        "thumb": "assets/gallery/christening/thumb/photo-1.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.0 \u00b7 1/200s \u00b7 ISO 640",
        "lighting": "Church Ambient Light",
        "colorProfile": "Documentary Tone \u00b7 High Clarity",
        "caption": "The pivotal sacrament moment framed with reverence and timing."
      },
      {
        "id": "ch-2",
        "title": "Godparent Blessing",
        "filename": "photo-2.jpg",
        "full": "assets/gallery/christening/full/photo-2.jpg",
        "thumb": "assets/gallery/christening/thumb/photo-2.jpg",
        "lens": "35mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.2 \u00b7 1/250s \u00b7 ISO 500",
        "lighting": "Cathedral Window Side Light",
        "colorProfile": "Natural Light Balance",
        "caption": "Sponsors gathered in prayer over the newborn."
      },
      {
        "id": "ch-3",
        "title": "Candlelit Procession",
        "filename": "photo-3.jpg",
        "full": "assets/gallery/christening/full/photo-3.jpg",
        "thumb": "assets/gallery/christening/thumb/photo-3.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/1.8 \u00b7 1/320s \u00b7 ISO 400",
        "lighting": "Candle Flame & Sanctuary Glow",
        "colorProfile": "Warm Golden Tone",
        "caption": "Atmospheric ceremony lighting captured without disruptive flash."
      },
      {
        "id": "ch-4",
        "title": "Infant Serenity",
        "filename": "photo-4.jpg",
        "full": "assets/gallery/christening/full/photo-4.jpg",
        "thumb": "assets/gallery/christening/thumb/photo-4.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.0 \u00b7 1/250s \u00b7 ISO 400",
        "lighting": "Soft Diffused Indoor",
        "colorProfile": "Pure Whites & Gentle Shadows",
        "caption": "Close portrait in white ceremonial vestments."
      },
      {
        "id": "ch-5",
        "title": "Altar Family Assembly",
        "filename": "photo-5.jpg",
        "full": "assets/gallery/christening/full/photo-5.jpg",
        "thumb": "assets/gallery/christening/thumb/photo-5.jpg",
        "lens": "35mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.8 \u00b7 1/160s \u00b7 ISO 800",
        "lighting": "Altar Overhead Fixtures",
        "colorProfile": "Architectural Harmony",
        "caption": "Wide group portrait under the cathedral archway."
      },
      {
        "id": "ch-6",
        "title": "Post-Sacrament Gathering",
        "filename": "photo-6.jpg",
        "full": "assets/gallery/christening/full/photo-6.jpg",
        "thumb": "assets/gallery/christening/thumb/photo-6.jpg",
        "lens": "35mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.2 \u00b7 1/320s \u00b7 ISO 320",
        "lighting": "Open Air Courtyard",
        "colorProfile": "Crisp Daylight Grade",
        "caption": "Candid celebration smiles outside the sanctuary doors."
      }
    ]
  },
  {
    "id": "colorgrading-test",
    "slug": "colorgrading-test",
    "title": "Cinematic Color & Film Curve Study",
    "client": "Personal Visual Research",
    "category": "editorial",
    "categoryLabel": "EDITORIAL / COLOR SCIENCE",
    "date": "2025\u20132026",
    "location": "Davao del Sur, Philippines",
    "cover": "assets/gallery/colorgrading-test/full/photo-1.jpg",
    "coverThumb": "assets/gallery/colorgrading-test/thumb/photo-1.jpg",
    "tagline": "Exploration of Kodak & Fuji film emulations and shadow roll-off.",
    "description": "A dedicated optical and color science test exploring custom LUTs, split-toning in DaVinci Resolve, and Kodak Vision3 dynamic range emulation on Nikon digital sensors.",
    "primaryCamera": "Nikon Full-Frame",
    "primaryLens": "55mm \u0192/1.8 Fast Prime",
    "lightingSetup": "Controlled Natural Light & Negative Fill",
    "colorScience": "DaVinci Resolve Studio \u00b7 3D LUT Film Curves",
    "photos": [
      {
        "id": "cg-1",
        "title": "Teal & Amber Shadow Separation",
        "filename": "photo-1.jpg",
        "full": "assets/gallery/colorgrading-test/full/photo-1.jpg",
        "thumb": "assets/gallery/colorgrading-test/thumb/photo-1.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/1.8 \u00b7 1/640s \u00b7 ISO 100",
        "lighting": "Soft Overcast Sky",
        "colorProfile": "Kodak 2383 Print Profile",
        "caption": "Subtle color contrast separating cold background shadows from warm skin tones."
      },
      {
        "id": "cg-2",
        "title": "Halation & Highlight Roll-off",
        "filename": "photo-2.jpg",
        "full": "assets/gallery/colorgrading-test/full/photo-2.jpg",
        "thumb": "assets/gallery/colorgrading-test/thumb/photo-2.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.0 \u00b7 1/1000s \u00b7 ISO 100",
        "lighting": "Harsh Rim Sun",
        "colorProfile": "Vintage Halation Simulation",
        "caption": "Testing digital sensor highlight compression without digital clipping."
      },
      {
        "id": "cg-3",
        "title": "Low-Key Tonal Density",
        "filename": "photo-3.jpg",
        "full": "assets/gallery/colorgrading-test/full/photo-3.jpg",
        "thumb": "assets/gallery/colorgrading-test/thumb/photo-3.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/1.8 \u00b7 1/400s \u00b7 ISO 200",
        "lighting": "Single Directional Window",
        "colorProfile": "Deep Muted Black Point",
        "caption": "Rich shadow detail retention in deep moody portraiture."
      },
      {
        "id": "cg-4",
        "title": "Earthy Matte Palette",
        "filename": "photo-4.jpg",
        "full": "assets/gallery/colorgrading-test/full/photo-4.jpg",
        "thumb": "assets/gallery/colorgrading-test/thumb/photo-4.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.2 \u00b7 1/500s \u00b7 ISO 125",
        "lighting": "Dappled Tree Light",
        "colorProfile": "Desaturated Foliage \u00b7 True Skin",
        "caption": "Harmonizing chaotic background greens with smooth skin luminance."
      },
      {
        "id": "cg-5",
        "title": "Monochrome Contrast Study",
        "filename": "photo-5.jpg",
        "full": "assets/gallery/colorgrading-test/full/photo-5.jpg",
        "thumb": "assets/gallery/colorgrading-test/thumb/photo-5.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/1.8 \u00b7 1/800s \u00b7 ISO 100",
        "lighting": "Side Profile Daylight",
        "colorProfile": "Ilford HP5 Plus Emulation",
        "caption": "High micro-contrast black-and-white conversion focusing strictly on form and texture."
      }
    ]
  },
  {
    "id": "debut-quin",
    "slug": "debut-quin",
    "title": "Debut Photoshoot of Quin",
    "client": "Quin's 18th Debut",
    "category": "portraits",
    "categoryLabel": "PORTRAITS / DEBUT",
    "date": "2026",
    "location": "Davao City, Philippines",
    "cover": "assets/gallery/debut-quin/full/photo-1.jpg",
    "coverThumb": "assets/gallery/debut-quin/thumb/photo-1.jpg",
    "tagline": "Elegant 18th debut editorial session with high-fashion aesthetics.",
    "description": "Crafting a sophisticated, timeless debut portfolio highlighting grace, gown textures, and dramatic natural lighting setups.",
    "primaryCamera": "Nikon Full-Frame",
    "primaryLens": "55mm \u0192/1.8 Prime",
    "lightingSetup": "Natural Backlight & Ambient Softbox Fill",
    "colorScience": "Editorial High-Contrast Glamour Grade",
    "photos": [
      {
        "id": "dq-1",
        "title": "The Debutante in Crimson",
        "filename": "photo-1.jpg",
        "full": "assets/gallery/debut-quin/full/photo-1.jpg",
        "thumb": "assets/gallery/debut-quin/thumb/photo-1.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.0 \u00b7 1/640s \u00b7 ISO 100",
        "lighting": "Soft Diffused Sunlight",
        "colorProfile": "Vibrant Red Saturation \u00b7 Clean Skin",
        "caption": "Striking full gown portrait with cinematic presence."
      },
      {
        "id": "dq-2",
        "title": "Gown Texture & Silhouette",
        "filename": "photo-2.jpg",
        "full": "assets/gallery/debut-quin/full/photo-2.jpg",
        "thumb": "assets/gallery/debut-quin/thumb/photo-2.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.2 \u00b7 1/500s \u00b7 ISO 125",
        "lighting": "Backlit Rim Light",
        "colorProfile": "Deep Shadows \u00b7 Rich Highlights",
        "caption": "Capturing intricate fabric details and graceful contour."
      },
      {
        "id": "dq-3",
        "title": "Close-Up Elegance",
        "filename": "photo-3.jpg",
        "full": "assets/gallery/debut-quin/full/photo-3.jpg",
        "thumb": "assets/gallery/debut-quin/thumb/photo-3.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/1.8 \u00b7 1/800s \u00b7 ISO 100",
        "lighting": "Soft Front Fill",
        "colorProfile": "Porcelain Skin Science",
        "caption": "Intimate headshot emphasizing makeup precision and expressive gaze."
      },
      {
        "id": "dq-4",
        "title": "Architectural Editorial",
        "filename": "photo-4.jpg",
        "full": "assets/gallery/debut-quin/full/photo-4.jpg",
        "thumb": "assets/gallery/debut-quin/thumb/photo-4.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.8 \u00b7 1/320s \u00b7 ISO 200",
        "lighting": "Mixed Ambient",
        "colorProfile": "Neutral Tonal Balance",
        "caption": "Framed within modern architectural backdrops."
      },
      {
        "id": "dq-5",
        "title": "Candid Transition Frame",
        "filename": "photo-5.jpg",
        "full": "assets/gallery/debut-quin/full/photo-5.jpg",
        "thumb": "assets/gallery/debut-quin/thumb/photo-5.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.0 \u00b7 1/500s \u00b7 ISO 160",
        "lighting": "Golden Hour Ambient",
        "colorProfile": "Warm Nostalgia Tone",
        "caption": "Relaxed in-between moment highlighting genuine emotion."
      }
    ]
  },
  {
    "id": "first-prime-lens",
    "slug": "first-prime-lens",
    "title": "First Prime Lens Optical Study",
    "client": "Visual Optics Archive",
    "category": "portraits",
    "categoryLabel": "OPTICS / PORTRAITS",
    "date": "2025",
    "location": "Mindanao, Philippines",
    "cover": "assets/gallery/first-prime-lens/full/photo-1.jpg",
    "coverThumb": "assets/gallery/first-prime-lens/thumb/photo-1.jpg",
    "tagline": "Testing 55mm wide-open bokeh and edge-to-edge sharpness.",
    "description": "The initial creative field tests of the 55mm prime optic: exploring shallow depth-of-field isolation, chromatic aberration control, and organic subject pop.",
    "primaryCamera": "Nikon Full-Frame",
    "primaryLens": "55mm \u0192/1.8 Prime",
    "lightingSetup": "Direct Sunlight & Open Shade",
    "colorScience": "Minimal Retouching \u00b7 Pure Optical Rendering",
    "photos": [
      {
        "id": "fpl-1",
        "title": "Wide Open \u0192/1.8 Separation",
        "filename": "photo-1.jpg",
        "full": "assets/gallery/first-prime-lens/full/photo-1.jpg",
        "thumb": "assets/gallery/first-prime-lens/thumb/photo-1.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/1.8 \u00b7 1/1250s \u00b7 ISO 100",
        "lighting": "Natural Sun",
        "colorProfile": "Direct Sensor Color",
        "caption": "Demonstrating razor-sharp focal plane with creamy circular background bokeh."
      },
      {
        "id": "fpl-2",
        "title": "Environmental Context",
        "filename": "photo-2.jpg",
        "full": "assets/gallery/first-prime-lens/full/photo-2.jpg",
        "thumb": "assets/gallery/first-prime-lens/thumb/photo-2.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.2 \u00b7 1/800s \u00b7 ISO 100",
        "lighting": "Dappled Foliage Shade",
        "colorProfile": "Natural Tonal Range",
        "caption": "Subject integrated smoothly into organic surroundings."
      },
      {
        "id": "fpl-3",
        "title": "Texture & Micro-Contrast",
        "filename": "photo-3.jpg",
        "full": "assets/gallery/first-prime-lens/full/photo-3.jpg",
        "thumb": "assets/gallery/first-prime-lens/thumb/photo-3.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.0 \u00b7 1/640s \u00b7 ISO 125",
        "lighting": "Diffused Window Light",
        "colorProfile": "High Clarity \u00b7 Fine Texture",
        "caption": "Resolving fine fabric threads and hair strands with high micro-contrast."
      },
      {
        "id": "fpl-4",
        "title": "Side-Profile Geometry",
        "filename": "photo-4.jpg",
        "full": "assets/gallery/first-prime-lens/full/photo-4.jpg",
        "thumb": "assets/gallery/first-prime-lens/thumb/photo-4.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/1.8 \u00b7 1/1000s \u00b7 ISO 100",
        "lighting": "Open Sky Ambient",
        "colorProfile": "Clean Neutral Grade",
        "caption": "Geometric lines and natural eye tracking."
      },
      {
        "id": "fpl-5",
        "title": "Golden Flare Test",
        "filename": "photo-5.jpg",
        "full": "assets/gallery/first-prime-lens/full/photo-5.jpg",
        "thumb": "assets/gallery/first-prime-lens/thumb/photo-5.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/1.8 \u00b7 1/1600s \u00b7 ISO 100",
        "lighting": "Direct Backlit Sunset",
        "colorProfile": "Warm Organic Flare",
        "caption": "Testing internal optical coating resistance against direct sun flare."
      }
    ]
  },
  {
    "id": "national-prisaa-2025",
    "slug": "national-prisaa-2025",
    "title": "NATIONAL PRISAA 2025 Games",
    "client": "Athletic Photojournalism",
    "category": "journalism",
    "categoryLabel": "SPORTS / PHOTOJOURNALISM",
    "date": "2025",
    "location": "Davao City Sports Complex, Philippines",
    "cover": "assets/gallery/national-prisaa-2025/full/photo-1.jpg",
    "coverThumb": "assets/gallery/national-prisaa-2025/thumb/photo-1.jpg",
    "tagline": "High-speed athletic photojournalism and championship drama.",
    "description": "Documenting national collegiate athletics: peak intensity, explosive motion freezing, emotional medal ceremonies, and collegiate sportsmanship.",
    "primaryCamera": "Nikon Full-Frame",
    "primaryLens": "Fast Telephoto & 55mm Optics",
    "lightingSetup": "Arena Floodlights & Blazing Outdoor Sun",
    "colorScience": "High-Contrast Sports Action Grade",
    "photos": [
      {
        "id": "pr-1",
        "title": "The Sprint Decider",
        "filename": "photo-1.jpg",
        "full": "assets/gallery/national-prisaa-2025/full/photo-1.jpg",
        "thumb": "assets/gallery/national-prisaa-2025/thumb/photo-1.jpg",
        "lens": "Fast Telephoto",
        "camera": "Nikon",
        "exposure": "\u0192/2.8 \u00b7 1/2500s \u00b7 ISO 400",
        "lighting": "Track Stadium Daylight",
        "colorProfile": "Dynamic Sports Color",
        "caption": "Peak athletic velocity frozen at the finish line."
      },
      {
        "id": "pr-2",
        "title": "Courtside Focus & Intensity",
        "filename": "photo-2.jpg",
        "full": "assets/gallery/national-prisaa-2025/full/photo-2.jpg",
        "thumb": "assets/gallery/national-prisaa-2025/thumb/photo-2.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.0 \u00b7 1/1600s \u00b7 ISO 800",
        "lighting": "Indoor Gymnasium Lights",
        "colorProfile": "High Clarity \u00b7 True Skin",
        "caption": "Athlete locked in concentration before serve execution."
      },
      {
        "id": "pr-3",
        "title": "Mid-Air Elevation",
        "filename": "photo-3.jpg",
        "full": "assets/gallery/national-prisaa-2025/full/photo-3.jpg",
        "thumb": "assets/gallery/national-prisaa-2025/thumb/photo-3.jpg",
        "lens": "Fast Telephoto",
        "camera": "Nikon",
        "exposure": "\u0192/2.8 \u00b7 1/2000s \u00b7 ISO 640",
        "lighting": "Gym Arena Floodlights",
        "colorProfile": "Punchy Vibrance & Deep Shadows",
        "caption": "Spike takeoff suspended at highest vertical jump point."
      },
      {
        "id": "pr-4",
        "title": "Team Huddle & Unity",
        "filename": "photo-4.jpg",
        "full": "assets/gallery/national-prisaa-2025/full/photo-4.jpg",
        "thumb": "assets/gallery/national-prisaa-2025/thumb/photo-4.jpg",
        "lens": "35mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.2 \u00b7 1/800s \u00b7 ISO 500",
        "lighting": "Courtside Ambient",
        "colorProfile": "Emotional Tonal Science",
        "caption": "Tactical timeout and collective championship determination."
      },
      {
        "id": "pr-5",
        "title": "The Victory Roar",
        "filename": "photo-5.jpg",
        "full": "assets/gallery/national-prisaa-2025/full/photo-5.jpg",
        "thumb": "assets/gallery/national-prisaa-2025/thumb/photo-5.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.0 \u00b7 1/1250s \u00b7 ISO 400",
        "lighting": "Open Arena Sun",
        "colorProfile": "High Dynamic Range Mastery",
        "caption": "Pure uninhibited celebration upon securing the gold medal point."
      }
    ]
  },
  {
    "id": "school-publication",
    "slug": "school-publication",
    "title": "Campus Journalism & Grand Opening",
    "client": "Cor Jesu College Publication",
    "category": "journalism",
    "categoryLabel": "CAMPUS JOURNALISM / EVENTS",
    "date": "2025\u20132026",
    "location": "Cor Jesu College, Digos City",
    "cover": "assets/gallery/school-publication/full/photo-1.jpg",
    "coverThumb": "assets/gallery/school-publication/thumb/photo-1.jpg",
    "tagline": "Official institutional photojournalism and campus history.",
    "description": "Documenting ribbon cuttings, university inaugurations, student leadership assemblies, and editorial publication spreads.",
    "primaryCamera": "Nikon Full-Frame",
    "primaryLens": "35mm \u0192/1.8 & 55mm \u0192/1.8",
    "lightingSetup": "Mixed Indoor Auditorium & Stage Spotlights",
    "colorScience": "Editorial Press Tones & True Corporate Identity",
    "photos": [
      {
        "id": "sp-1",
        "title": "Grand Inauguration Ribbon Cutting",
        "filename": "photo-1.jpg",
        "full": "assets/gallery/school-publication/full/photo-1.jpg",
        "thumb": "assets/gallery/school-publication/thumb/photo-1.jpg",
        "lens": "35mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.8 \u00b7 1/320s \u00b7 ISO 400",
        "lighting": "Outdoor Courtyard Sunlight",
        "colorProfile": "Crisp Press Tones",
        "caption": "University administrators and student leaders inaugurating new campus facilities."
      },
      {
        "id": "sp-2",
        "title": "Auditorium Address",
        "filename": "photo-2.jpg",
        "full": "assets/gallery/school-publication/full/photo-2.jpg",
        "thumb": "assets/gallery/school-publication/thumb/photo-2.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.0 \u00b7 1/250s \u00b7 ISO 640",
        "lighting": "Podium Keylight",
        "colorProfile": "High Tonal Separation",
        "caption": "Keynote speaker addressing the student body assembly."
      },
      {
        "id": "sp-3",
        "title": "Student Publication Editorial Room",
        "filename": "photo-3.jpg",
        "full": "assets/gallery/school-publication/full/photo-3.jpg",
        "thumb": "assets/gallery/school-publication/thumb/photo-3.jpg",
        "lens": "35mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.0 \u00b7 1/160s \u00b7 ISO 800",
        "lighting": "Ambient Room Fluorescent + Natural",
        "colorProfile": "Balanced White Balance",
        "caption": "Student journalists collaborating on deadline layouts."
      },
      {
        "id": "sp-4",
        "title": "Faculty & Leadership Assembly",
        "filename": "photo-4.jpg",
        "full": "assets/gallery/school-publication/full/photo-4.jpg",
        "thumb": "assets/gallery/school-publication/thumb/photo-4.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.2 \u00b7 1/320s \u00b7 ISO 500",
        "lighting": "Auditorium Ambient",
        "colorProfile": "Institutional Color Fidelity",
        "caption": "Faculty leaders conferring during ceremonial proceedings."
      },
      {
        "id": "sp-5",
        "title": "Campus Golden Hour Walkway",
        "filename": "photo-5.jpg",
        "full": "assets/gallery/school-publication/full/photo-5.jpg",
        "thumb": "assets/gallery/school-publication/thumb/photo-5.jpg",
        "lens": "35mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/1.8 \u00b7 1/640s \u00b7 ISO 100",
        "lighting": "Afternoon Golden Sun",
        "colorProfile": "Warm Campus Memory Tone",
        "caption": "Everyday university student life framed against sunset campus architecture."
      }
    ]
  },
  {
    "id": "wedding-shots",
    "slug": "wedding-shots",
    "title": "Intimate Wedding & Sacred Vows",
    "client": "Private Wedding Archive",
    "category": "wedding",
    "categoryLabel": "WEDDING / CEREMONY",
    "date": "2025\u20132026",
    "location": "Davao Region, Philippines",
    "cover": "assets/gallery/wedding-shots/full/photo-1.jpg",
    "coverThumb": "assets/gallery/wedding-shots/thumb/photo-1.jpg",
    "tagline": "Unforced romance, vows exchange, and ceremonial elegance.",
    "description": "Documenting vows, wedding ring details, candid tears of joy, and golden-hour couple portraiture with heartfelt subtlety and reverence.",
    "primaryCamera": "Nikon Full-Frame",
    "primaryLens": "35mm \u0192/1.8 & 55mm \u0192/1.8",
    "lightingSetup": "Golden Hour Ambient & Church Stained Glass",
    "colorScience": "Timeless Romantic Film Curve & Creamy Skin Tones",
    "photos": [
      {
        "id": "wd-1",
        "title": "Golden Hour Vow Exchange",
        "filename": "photo-1.jpg",
        "full": "assets/gallery/wedding-shots/full/photo-1.jpg",
        "thumb": "assets/gallery/wedding-shots/thumb/photo-1.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/1.8 \u00b7 1/1000s \u00b7 ISO 100",
        "lighting": "Golden Sunset Backlight",
        "colorProfile": "Warm Cinematic Romance",
        "caption": "The bride and groom sharing private vows as the sun dips below the horizon."
      },
      {
        "id": "wd-2",
        "title": "Sacred Wedding Bands",
        "filename": "photo-2.jpg",
        "full": "assets/gallery/wedding-shots/full/photo-2.jpg",
        "thumb": "assets/gallery/wedding-shots/thumb/photo-2.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.8 \u00b7 1/250s \u00b7 ISO 200",
        "lighting": "Soft Window Light",
        "colorProfile": "Intricate Macro Clarity",
        "caption": "Gold wedding bands resting on sacred prayer text."
      },
      {
        "id": "wd-3",
        "title": "The Bridal March",
        "filename": "photo-3.jpg",
        "full": "assets/gallery/wedding-shots/full/photo-3.jpg",
        "thumb": "assets/gallery/wedding-shots/thumb/photo-3.jpg",
        "lens": "35mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.0 \u00b7 1/320s \u00b7 ISO 500",
        "lighting": "Church Aisle Sunlight",
        "colorProfile": "Pure White Veil Science",
        "caption": "Emotional aisle entrance framed with full architectural depth."
      },
      {
        "id": "wd-4",
        "title": "The First Kiss as Husband & Wife",
        "filename": "photo-4.jpg",
        "full": "assets/gallery/wedding-shots/full/photo-4.jpg",
        "thumb": "assets/gallery/wedding-shots/thumb/photo-4.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.0 \u00b7 1/400s \u00b7 ISO 400",
        "lighting": "Sanctuary Ambient",
        "colorProfile": "Timeless Editorial Contrast",
        "caption": "Celebration applause erupting as vows are sealed."
      },
      {
        "id": "wd-5",
        "title": "Veil & Wind in the Field",
        "filename": "photo-5.jpg",
        "full": "assets/gallery/wedding-shots/full/photo-5.jpg",
        "thumb": "assets/gallery/wedding-shots/thumb/photo-5.jpg",
        "lens": "55mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/1.8 \u00b7 1/1250s \u00b7 ISO 100",
        "lighting": "Outdoor Breeze & Sun",
        "colorProfile": "Dreamy Highlight Bloom",
        "caption": "Blowing veil movement capturing romance and natural grace."
      },
      {
        "id": "wd-6",
        "title": "Candid Reception Laughter",
        "filename": "photo-6.jpg",
        "full": "assets/gallery/wedding-shots/full/photo-6.jpg",
        "thumb": "assets/gallery/wedding-shots/thumb/photo-6.jpg",
        "lens": "35mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/2.2 \u00b7 1/200s \u00b7 ISO 800",
        "lighting": "Fairy Lights & Candle Glow",
        "colorProfile": "Warm Night Ambiance",
        "caption": "Spontaneous toast and family celebration laughter."
      },
      {
        "id": "wd-7",
        "title": "Evening Send-Off Sparklers",
        "filename": "photo-7.jpg",
        "full": "assets/gallery/wedding-shots/full/photo-7.jpg",
        "thumb": "assets/gallery/wedding-shots/thumb/photo-7.jpg",
        "lens": "35mm \u0192/1.8",
        "camera": "Nikon",
        "exposure": "\u0192/1.8 \u00b7 1/160s \u00b7 ISO 1250",
        "lighting": "Sparkler Trails & Night Ambient",
        "colorProfile": "Golden Sparkler Glow",
        "caption": "Luminous exit framed through lines of glowing sparklers."
      }
    ]
  }
];
